<address>
Copyright &#169; VIP Services. All Rights Reserved &bull; P.O. Box 818 &bull; Clyde, TX 79510 &bull; (325) 893-3361<br>
Email: <a href="mailto:VIPServicesTexas@gmail.com">VIPServicesTexas@gmail.com</a><br>
<!-- Site Powered by: <A HREF = "http://www.2k3technologies.com">2k3 Technologies</A><br> -->
<?php
  //print "URL: http://" . $_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'] . "<br>\n";
  print "Last Refreshed: ";
  print date("l F d, Y : h:i A",  filemtime($_SERVER['SCRIPT_FILENAME']));
 ?>
<br />Site Maintained and Hosted by <a href="http://www.jdacsolutions.com">JDAC Solutions</a>
</address>
